[package]
name = "rust-system-profiler"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = {version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
structopt = "0.3.26"
sysinfo = "0.31.1"
